### ISSUE TITLE
Drawing circles with the arm

### ISSUE THREAD

**Issue by garimellagowtham** [dorna-robotics/dorna#11]
Hello @smhty ,
I bought the Dorna arm recently. I am trying to draw a circle using the robotic arm. Currently, there is no direct command to draw a circle. I can generate a circular arc by breaking it into several line segments. But that process will be slow and unwieldy since the robot slows down to stop at each waypoint.

Is there any way of forwarding a circle command to the robot. If not, I would like to add that to the API. I understand that the python code forwards commands to Arduino due which is running a modified version of g2core. I do not have access to the version of g2core that is being used or how to update that.

Can you provide the steps on how to modify the Arduino due firmware or how to send a circular arc command to the robotic arm?

Thanks,
Gowtham.

**Comment by smhty** [comment]
@garimellagowtham 
At this point we do not have integrated the ARC move (circle) in the API.
But you can always directly send g2core commands, using 
`{"command": "g2core", "prm": "..."}`

The value assigned to the `prm` key is the g2core command here.
For example, the following command returns the status report of the firmware.
 `{"command": "g2core", "prm": "{sr:n}"}`

In your case to draw a circle you can use `G2 or G3` commands. For the full documentation visit this link:
https://github.com/synthetos/g2/wiki/G2-G3-Arc-At-Feed-Rate

There are also few things that you have to consider before drawing the circle:

- Since you want the circle in the  Cartesian space (I assume), make sure to run a simple line move command to shift the space from joint to Cartesian: `{"command": "move", "prm": {"path": "line", "movement": 1, "x":0}}`. After this it is safe to draw a circle.
- Also make sure that all the points in the circle path is a valid Cartesian point for the robot (achievable).

I tested the circle myself and it works very well. I have also planned to include it in the API, and make it a like a simple move command.
Let me know if you want to help us with it, or you have any other idea.

Best,
Hossein

**Comment by garimellagowtham** [comment]
I will try to that over the weekend and try to add that to the API.

**Comment by garimellagowtham** [comment]
#13

**Comment by smhty** [comment]
@garimellagowtham I will go over your code, and test it.
