### ISSUE TITLE
Permission settings for save_config() function

### ISSUE THREAD

**Issue by mfogelson** [dorna-robotics/dorna#3]
When running robot.save_config() you get:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/dorna-1.3-py3.6.egg/dorna/config.yaml'                                                                               

This goes away if you run sudo or sudo -s before running the script, but maybe you could change the permissions when downloading everything?

**Comment by smhty** [comment]
This is a problem with Linux and Mac. 
I actually don't know about your suggestion: "maybe you could change the permissions when downloading everything". If you can explain it more to me.
One option is to the make sure that the user has a sudo access when they are initializing the Dorna object.

**Comment by justinclift** [comment]
Ahhh.  The path this is showing points out the problem:

```
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/dorna-1.3-py3.6.egg/dorna/config.yaml'
```

On most versions of *nix, paths like `/usr/local/lib/ ...` are kept for system files.  It sounds like the dorna-1.3 files are being installed there, which is the correct place.  Those paths are generally considered "read only", because user software shouldn't have write access to system paths. :wink:

The general approach is to have user software save config value to the user's home directory (eg `$HOME/.dorna/config.yaml`).  That keeps the separation between system software + user saved values.

Does that help? :smile:

**Comment by mfogelson** [comment]
Yes, 
These suggestions all make sense!
